In [53]:
# import libraries
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image, ImageDraw

In [54]:
genomes =[]
for i in range(4):
    genomes.append([np.random.randint(2, size=6)]) # add 5 randomly initialised indiviudals

In [55]:
acc= [50.8,0.9,0.3,0.4]

In [56]:
#paring
print(genomes)
s= genomes[1]
d = genomes[0]
a = s[0]
b = d[0]
child= [3,3,3,3,3,3]
print(a)
print(b)
childa = np.concatenate((a[:3], b[3:]), axis=0)



print(childa)

[[array([1, 1, 0, 0, 1, 0])], [array([1, 0, 0, 0, 0, 1])], [array([1, 0, 1, 0, 0, 0])], [array([1, 1, 0, 0, 1, 1])]]
[1 0 0 0 0 1]
[1 1 0 0 1 0]
[5 4 4]
[1 0 0 0 1 0]
