In [1]:
# import libraries
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image, ImageDraw
import random

Using TensorFlow backend.


In [2]:
genomes =[]
for i in range(4):
    genomes.append([np.random.randint(2, size=6)]) # add 5 randomly initialised indiviudals
    
print(genomes)

[[array([0, 1, 1, 0, 1, 0])], [array([1, 0, 0, 0, 1, 0])], [array([0, 1, 1, 1, 0, 1])], [array([0, 1, 1, 1, 1, 1])]]


In [3]:
acc= [0.8,0.9,0.3,0.81]
print(acc)

[0.8, 0.9, 0.3, 0.81]


In [4]:
def selected(maxis, actualpop):
    childs= []
    maxis= np.array(maxis)
    indices = maxis.argsort()[-4:][::-1]
    print('Highest acc at')
    print(indices)
    parents= []
    
   
    for ind in indices:    
        parents.append(actualpop[ind])
            
   
    
    random.shuffle(parents)
    f= 0
    
    #### was passiert ungerade zahl geht nicht und 50 eltern überleben
    # 1 un2 2un3
    while f < len(parents)-1: 
        mom = parents[f]
        f= f +1
        dad = parents[f]     
        child = paring(mom,dad)
        childs.append(child)
        child = paring(dad,mom)
        childs.append(child)
        
    parents = parents.append(childs) 
    return parents
        
    

def paring(mom,dad):
    return(np.concatenate((mom[:3], dad[3:]), axis=0))

def entschachteln(genos):
    print(len(genos))
    neue = [0,0]
    i = 0
    for k in genos:
        for l in k:
            print(l)
            neue[i] =l
            i = i+1

    return (neue)

In [5]:
def fortpflanzung (maxis, actualpop):
    childs= []
    maxis= np.array(maxis)
    indices = maxis.argsort()[-3:][::-1]
    print('Highest acc at')
    print(indices)
    parents= []
    
    
    for ind in indices:    
        parents.append(actualpop[ind])
   
    random.shuffle(parents)
    
    f= 0
    parents = entschachteln(parents)
#     while f < len(parents)-1: 
#         mom = parents[f]
#         f= f +1
#         dad = parents[f]    
        
# #         decider = random.uniform(0, 1) # decides random how the cross-over works
# #         if decider < 0.5 :
# #             child = paring(mom,dad)
# #             childs.append(child)
# #         else:
# #             child = paring(dad,mom)
# #             childs.append(child)

    
#         child = paring(mom,dad)
#         childs.append(child)
    
#             child = paring(dad,mom)
#             childs.append(child)

    while f < len(parents)-1: 
        mom = parents[f]
        f= f +1
        dad = parents[f]     
        child = paring(mom,dad)
        childs.append(child)
        child = paring(dad,mom)
        childs.append(child)
    
    parents = np.concatenate((parents, childs), axis=0) 
    return parents
        
        

In [6]:
print(genomes)
print(acc)
print(fortpflanzung(acc, genomes))

[[array([0, 1, 1, 0, 1, 0])], [array([1, 0, 0, 0, 1, 0])], [array([0, 1, 1, 1, 0, 1])], [array([0, 1, 1, 1, 1, 1])]]
[0.8, 0.9, 0.3, 0.81]
Highest acc at
[1 3]
2
[0 1 1 1 1 1]
[1 0 0 0 1 0]
P
[array([0, 1, 1, 1, 1, 1]), array([1, 0, 0, 0, 1, 0])]
C
[array([0, 1, 1, 0, 1, 0]), array([1, 0, 0, 1, 1, 1])]
[[0 1 1 1 1 1]
 [1 0 0 0 1 0]
 [0 1 1 0 1 0]
 [1 0 0 1 1 1]]


In [7]:



def mutation(popul):
    position = random.randrange(0, len(genomes))
    gencode = popul[position]
    
    decider = random.uniform(0, 1)
    posi = 0
    if decider < 0.2 :
        posi = random.randrange(0, len(gencode))
    
        if gencode[posi] == 1:
            gencode[posi] = 0
        elif gencode[posi] == 0:
            gencode[posi] = 1
            
    popul[position] = np.array(gencode)
    
    return popul
    
    
    
        
    

print(mutation(genomes))

[[array([0, 1, 1, 0, 1, 0])], [array([1, 0, 0, 0, 1, 0])], [array([0, 1, 1, 1, 0, 1])], array([[0, 1, 1, 1, 1, 1]])]
